# Generated by Django 5.2.4 on 2025-07-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_smsverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSVerification',
        ),
    ]
