# Generated by Django 5.2.4 on 2025-07-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_email_verified_emailverification_and_more'),
    ]

    operations = [
    ]
