# Generated by Django 5.2.4 on 2025-07-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0002_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='scope',
            field=models.CharField(choices=[('local', 'Local'), ('state', 'State/Provincial'), ('national', 'National'), ('international', 'International')], default='local', max_length=20),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country', 'state', 'city'],
                'unique_together': {('country', 'state', 'city')},
            },
        ),
        migrations.AddField(
            model_name='raffle',
            name='allowed_locations',
            field=models.ManyToManyField(blank=True, related_name='raffles', to='rifas.location'),
        ),
    ]
