# Generated by Django 5.2.4 on 2025-07-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0004_update_scope_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='draw_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_ticket',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
